# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8d3047070aad33f204087e35d5e858c2efb116d683094eb2abd0f51e50239cd362956c725bd59d02ce3726321e4b09ae72a3c26568d21c5f0a612d87289378

test:
  secret_key_base: 2e77e7e7f9369aab2b06d437d224e0b4836078ca3eded44bb86e107e4bc92919a56fb8813d3d7f7580a2382c81f7328bbaac6b4a40ca1882fe4f1e448dfb368d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
